package com.android.hiparker.lierda_light.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupsDaoConfig;
    private final DaoConfig lightDaoConfig;

    private final GroupsDao groupsDao;
    private final LightDao lightDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        lightDaoConfig = daoConfigMap.get(LightDao.class).clone();
        lightDaoConfig.initIdentityScope(type);

        groupsDao = new GroupsDao(groupsDaoConfig, this);
        lightDao = new LightDao(lightDaoConfig, this);

        registerDao(Groups.class, groupsDao);
        registerDao(LightTemp.class, lightDao);
    }
    
    public void clear() {
        groupsDaoConfig.getIdentityScope().clear();
        lightDaoConfig.getIdentityScope().clear();
    }

    public GroupsDao getGroupsDao() {
        return groupsDao;
    }

    public LightDao getLightDao() {
        return lightDao;
    }
}
