package com.android.hiparker.lierda_light.dao;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GROUPS".
 */
public class Groups implements Serializable {

    private Long id;
    /** Not-null value. */
    private String name;
    private String lights;
    private String groupLights;
    private int value1; // color
    private int value2; // isOpen
    private int value3; // lightness
    private int value4; // colorTemperature

    public Groups() {
    }

    public Groups(Long id) {
        this.id = id;
    }

    public Groups(Long id, String name, String lights, int value1, int value2, int value3, int value4) {
        this.id = id;
        this.name = name;
        this.lights = lights;
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
        this.value4 = value4;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getLights() {
        return lights;
    }

    public void setLights(String lights) {
        this.lights = lights;
    }


    public void setGroupLights(String lights) {
        this.groupLights = lights;
    }


    public int getValue1() {
    	return value1;
    }
    
    public void setValue1(int value) {
    	value1 = value;
    }
    
    public int getValue2() {
    	return value2;
    }
    
    public void setValue2(int value) {
    	value2 = value;
    }
    
    public int getValue3() {
    	return value3;
    }
    
    public void setValue3(int value) {
    	value3 = value;
    }
    
    public int getValue4() {
    	return value4;
    }
    
    public void setValue4(int value) {
    	value4 = value;
    }

}
