package com.android.hiparker.lierda_light.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LIGHT".
 */
public class LightTemp {

    private String address;
    private String name;
    private Integer color;
    private Integer value1;
    private Integer value2;
    private Integer value3;
    private Integer value4;

    public LightTemp() {
    }

    public LightTemp(String address) {
        this.address = address;
    }

    public LightTemp(String address, String name, Integer color, Integer value1, Integer value2, Integer value3, Integer value4) {
        this.address = address;
        this.name = name;
        this.color = color;
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
        this.value4 = value4;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getColor() {
        return color;
    }

    public void setColor(Integer color) {
        this.color = color;
    }

    public Integer getValue1() {
        return value1;
    }

    public void setValue1(Integer value1) {
        this.value1 = value1;
    }

    public Integer getValue2() {
        return value2;
    }

    public void setValue2(Integer value2) {
        this.value2 = value2;
    }

    public Integer getValue3() {
        return value3;
    }

    public void setValue3(Integer value3) {
        this.value3 = value3;
    }

    public Integer getValue4() {
        return value4;
    }

    public void setValue4(Integer value4) {
        this.value4 = value4;
    }

}
